# Phase 3 Demo — Sudoku Solver

This notebook simply imports that module and shows it running on a few example boards

In [2]:
import sys, time
sys.path.insert(0, '.')
import numpy as np
from solver.sudoku_solver import solve_sudoku, is_valid_board

## 1. A standard solvable puzzle

In [3]:
puzzle = [
    [5, 3, 0, 0, 7, 0, 0, 0, 0],
    [6, 0, 0, 1, 9, 5, 0, 0, 0],
    [0, 9, 8, 0, 0, 0, 0, 6, 0],
    [8, 0, 0, 0, 6, 0, 0, 0, 3],
    [4, 0, 0, 8, 0, 3, 0, 0, 1],
    [7, 0, 0, 0, 2, 0, 0, 0, 6],
    [0, 6, 0, 0, 0, 0, 2, 8, 0],
    [0, 0, 0, 4, 1, 9, 0, 0, 5],
    [0, 0, 0, 0, 8, 0, 0, 7, 9],
]

success, solved = solve_sudoku(puzzle)
print("Solved:", success)
for row in solved:
    print(row)

Solved: True
[5, 3, 4, 6, 7, 8, 9, 1, 2]
[6, 7, 2, 1, 9, 5, 3, 4, 8]
[1, 9, 8, 3, 4, 2, 5, 6, 7]
[8, 5, 9, 7, 6, 1, 4, 2, 3]
[4, 2, 6, 8, 5, 3, 7, 9, 1]
[7, 1, 3, 9, 2, 4, 8, 5, 6]
[9, 6, 1, 5, 3, 7, 2, 8, 4]
[2, 8, 7, 4, 1, 9, 6, 3, 5]
[3, 4, 5, 2, 8, 6, 1, 7, 9]


## 2. NumPy input/output (matches Phase 2's array format)

In [4]:
np_puzzle = np.array(puzzle)
success, solved = solve_sudoku(np_puzzle)
print("Type of result:", type(solved))
print(solved)

Type of result: <class 'numpy.ndarray'>
[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]


## 3. An inconsistent board (simulated Phase 2 misclassification)

Two `5`s in the same row — this is the kind of error a noisy digit classifier could produce. The solver should reject it cleanly instead of crashing.

In [5]:
bad_puzzle = [row[:] for row in puzzle]
bad_puzzle[0][1] = 5  # duplicate 5 in row 0

success, solved = solve_sudoku(bad_puzzle)
print("Solved:", success, "| Result:", solved)

Solved: False | Result: None


## 4. Timing across difficulty levels

Reproduces the performance table from the Phase 3 writeup.

In [6]:
hard_17_clue = [
    [8, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 3, 6, 0, 0, 0, 0, 0],
    [0, 7, 0, 0, 9, 0, 2, 0, 0],
    [0, 5, 0, 0, 0, 7, 0, 0, 0],
    [0, 0, 0, 0, 4, 5, 7, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 3, 0],
    [0, 0, 1, 0, 0, 0, 0, 6, 8],
    [0, 0, 8, 5, 0, 0, 0, 1, 0],
    [0, 9, 0, 0, 0, 0, 4, 0, 0],
]
empty_board = [[0] * 9 for _ in range(9)]

for name, b in [("medium/original puzzle", puzzle), ("empty board", empty_board), ("hard 17-clue", hard_17_clue)]:
    t0 = time.time()
    success, _ = solve_sudoku(b)
    dt = time.time() - t0
    print(f"{name:25s} solved={success}  time={dt:.4f}s")

medium/original puzzle    solved=True  time=0.0174s
empty board               solved=True  time=0.0013s
hard 17-clue              solved=True  time=0.1997s
